### ISSUE TITLE
ValueError: unconverted data remains: .405Z [Linux Mint 19.3]

### ISSUE THREAD

**Issue by firepainting** [bneijt/autotrash#26]
Hi,

This is similar to #15 but happens only on one of my two PCs on Linux Mint 19.3 (the other PC runs it fine).

$ autotrash -d 30
Traceback (most recent call last):
  File "/usr/bin/autotrash", line 317, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/autotrash", line 251, in main
    file_time = trash_info_date(file_name)
  File "/usr/bin/autotrash", line 101, in trash_info_date
    return time.strptime(parser.get(section, key), '%Y-%m-%dT%H:%M:%S')
  File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
    return _strptime(data_string, format)[0]
  File "/usr/lib/python2.7/_strptime.py", line 335, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: .405Z

Thank you.

**Comment by bneijt** [comment]
The code referenced in the stacktrace seems to be an old version of autotrash. Maybe you have a ~/.local/bin/autotrash that is older or a system-wide install that is an older version.

Try autotrash --version on both systems and compare the difference.

**Comment by bneijt** [comment]
No feedback for a while, so closing this issue as out-dated.
