### ISSUE TITLE
PackageNotFoundError not ignored when looking for package version

### ISSUE THREAD

**Issue by bneijt** [bneijt/autotrash#55]
When looking for the package version, we might hit
```
Traceback (most recent call last):
  File "/usr/bin/autotrash", line 33, in <module>
    sys.exit(load_entry_point('autotrash==0.4.4', 'console_scripts', 'autotrash')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/autotrash", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for autotrash
```
in certain install environments. This should just be ignored to result in a working autotrash without the version being known at runtime.

**Comment by MithicSpirit** [comment]
I believe that this was addressed by #59, so this and #56 should be closed.
